import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Hello from "../app/index";
import Script from "next/script";
import Page from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: {
  children: React.ReactNode;
}
) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <Page/>
        {children}
      </body>
    </html>
  );
}
